# Generated by Django 5.1.4 on 2025-01-15 15:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('cantidad_becados', models.IntegerField()),
                ('jefe_apto', models.CharField(max_length=100)),
                ('profesor_atiende', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Becado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('numero_identidad', models.CharField(max_length=11, unique=True, verbose_name='Número de identidad')),
                ('direccion_particular', models.TextField(verbose_name='Dirección Particular')),
                ('año', models.PositiveIntegerField(verbose_name='Año que cursa')),
                ('carrera', models.CharField(max_length=100, verbose_name='Carrera')),
                ('evaluacion_jefe_residencia', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)], verbose_name='Evaluación del Jefe de Residencia')),
                ('evaluacion_jefe_apto', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)], verbose_name='Evaluación del Jefe de Apartamento')),
                ('evaluacion_profesor', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)], verbose_name='Evaluación del Profesor')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='becados', to='residencia.apartamento')),
            ],
            options={
                'verbose_name': 'Becado',
                'verbose_name_plural': 'Becados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_apartamentos', models.IntegerField()),
                ('jefe_consejo', models.CharField(max_length=100)),
                ('profesor_atiende', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BecadoExtranjero',
            fields=[
                ('becado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='residencia.becado')),
                ('pais_procedencia', models.CharField(max_length=100, verbose_name='País de Procedencia')),
                ('numero_pasaporte', models.CharField(max_length=50, unique=True, verbose_name='Número de Pasaporte')),
                ('direccion_embajada', models.TextField(verbose_name='Dirección de la Embajada')),
                ('año_entrada', models.PositiveIntegerField(verbose_name='Año de Entrada al País')),
                ('evaluacion_relaciones_internacionales', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)], verbose_name='Evaluación del Jefe de Relaciones Internacionales')),
            ],
            options={
                'verbose_name': 'Becado Extranjero',
                'verbose_name_plural': 'Becados Extranjeros',
            },
            bases=('residencia.becado',),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='residencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residencia.residencia'),
        ),
    ]
