# Generated by Django 5.1.4 on 2025-01-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='becado',
            name='pais',
            field=models.CharField(default='Cuba', max_length=100, verbose_name='País de Origen'),
        ),
    ]
