# Generated by Django 5.1.4 on 2025-01-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0002_becado_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='capacidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
