# Generated by Django 5.1.4 on 2025-01-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0003_apartamento_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='evaluacion_apto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='numero',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
